<?php

return [
    [
        'name' => 'type',
        'title' => '水印开关',
        'type' => 'radio',
        'content' => [
            '关闭水印',
            '图片水印',
            '文字水印',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '是否开启水印',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'font',
        'title' => '水印字体',
        'type' => 'image',
        'content' => [],
        'value' => '/assets/fonts/SourceHanSansK-Regular.ttf',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'size',
        'title' => '文字大小',
        'type' => 'number',
        'content' => [],
        'value' => '20',
        'rule' => 'required',
        'msg' => '',
        'tip' => '字体大小，px格式',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'color',
        'title' => '水印字体颜色',
        'type' => 'string',
        'content' => [],
        'value' => '#ffffff',
        'rule' => 'required',
        'msg' => '',
        'tip' => '水印字体颜色',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'text',
        'title' => '文字内容',
        'type' => 'string',
        'content' => [],
        'value' => 'ceshi',
        'rule' => 'required',
        'msg' => '',
        'tip' => '水印文字内容',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'images',
        'title' => '水印图片',
        'type' => 'image',
        'content' => [],
        'value' => '/assets/addons/sythumb/img/logo.png',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '水印图片位置',
        'extend' => '',
    ],
    [
        'name' => 'quality',
        'title' => '图片质量',
        'type' => 'number',
        'content' => [],
        'value' => '100',
        'rule' => 'required',
        'msg' => '',
        'tip' => '水印文字内容',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'diaphaneity',
        'title' => '水印图片透明度',
        'type' => 'number',
        'content' => [],
        'value' => '80',
        'rule' => 'required',
        'msg' => '',
        'tip' => '水印图片透明度',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'location',
        'title' => '水印图片位置',
        'type' => 'radio',
        'content' => [
            1 => '左上角',
            '上居中',
            '右上角',
            '左居中',
            '正居中',
            '右居中',
            '左下角',
            '下居中',
            '右下角',
        ],
        'value' => '5',
        'rule' => 'required',
        'msg' => '',
        'tip' => '水印图片位置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'deploy',
        'title' => '图片缩放配置',
        'type' => 'radio',
        'content' => [
            '关闭裁剪',
            '等比例缩放',
            '居中裁剪',
            '左上角裁剪',
            '右下角裁剪',
            '固定尺寸缩放',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '缩放配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'zoomwith',
        'title' => '宽度',
        'type' => 'number',
        'content' => [],
        'value' => '800',
        'rule' => 'required',
        'msg' => '',
        'tip' => '图片宽度',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'zoomheight',
        'title' => '高度',
        'type' => 'number',
        'content' => [],
        'value' => '1800',
        'rule' => 'required',
        'msg' => '',
        'tip' => '图片高度',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'offset',
        'title' => '偏移度',
        'type' => 'number',
        'content' => [],
        'value' => '-20',
        'rule' => 'required',
        'msg' => '',
        'tip' => '偏移度',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'replace',
        'title' => '覆盖原图',
        'type' => 'radio',
        'content' => [
            '否',
            '是',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '此项为是时，后缀不生效',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ext',
        'title' => '文件后缀',
        'type' => 'string',
        'content' => [],
        'value' => '-thumb',
        'rule' => 'required',
        'msg' => '',
        'tip' => '最终效果a-thumb.jpg',
        'ok' => '',
        'extend' => '',
    ],
];
