<?php

return [
    [
        'name' => 'qq',
        'title' => 'QQ',
        'type' => 'array',
        'content' => [
            'app_id' => '',
            'app_secret' => '',
            'scope' => 'get_user_info',
        ],
        'value' => [
            'app_id' => '100000000',
            'app_secret' => '123456',
            'scope' => 'get_user_info',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wechat',
        'title' => '微信公众号',
        'type' => 'array',
        'content' => [
            'app_id' => '',
            'app_secret' => '',
            'callback' => '',
            'scope' => 'snsapi_base',
        ],
        'value' => [
            'app_id' => '100000000',
            'app_secret' => '123456',
            'scope' => 'snsapi_userinfo',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wechatweb',
        'title' => '微信网站应用',
        'type' => 'array',
        'content' => [
            'app_id' => '',
            'app_secret' => '',
            'callback' => '',
            'scope' => 'snsapi_login',
        ],
        'value' => [
            'app_id' => '100000000',
            'app_secret' => '123456',
            'scope' => 'snsapi_login',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'weibo',
        'title' => '微博',
        'type' => 'array',
        'content' => [
            'app_id' => '',
            'app_secret' => '',
            'scope' => 'get_user_info',
        ],
        'value' => [
            'app_id' => '100000000',
            'app_secret' => '123456',
            'scope' => 'get_user_info',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wechatmini',
        'title' => '微信小程序',
        'type' => 'array',
        'content' => [
            'app_id' => '',
            'app_secret' => '',
            'scope' => 'get_user_info',
        ],
        'value' => [
            'app_id' => 'wxa13f531ac61b2724',
            'secret' => 'd220e92c0fa6bb5d3b01c9f1d6e84630',
            'scope' => 'get_user_info',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'bindaccount',
        'title' => '账号绑定',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '是否开启账号绑定，关闭则自动创建账号',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'status',
        'title' => '第三方登录开关',
        'type' => 'checkbox',
        'content' => [
            'qq' => 'QQ',
            'wechat' => '微信',
            'weibo' => '微博',
        ],
        'value' => 'wechat',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '第三方登录开关',
        'extend' => '',
    ],
    [
        'name' => 'rewrite',
        'title' => '伪静态',
        'type' => 'array',
        'content' => [],
        'value' => [
            'index/index' => '/third$',
            'index/connect' => '/third/connect/[:platform]',
            'index/callback' => '/third/callback/[:platform]',
            'index/bind' => '/third/bind/[:platform]',
            'index/unbind' => '/third/unbind/[:platform]',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'array',
        'content' => [],
        'value' => '在微信内<b>微信登录</b>将调用微信公众号授权登录，微信外<b>微信登录</b>将调用微信网站应用授权登录',
        'rule' => '',
        'msg' => '',
        'tip' => '微信参数配置',
        'ok' => '',
        'extend' => '',
    ],
];
